/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `student`;

CREATE TABLE `student` (
  `sn` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` INT NULL,
  `score` DOUBLE NULL,
  `birthday` DATETIME NULL)
 ENGINE=InnoDB;

